### ISSUE TITLE
duplicate peptideEvidence id: timsTOF data with the latest MSGF+

### ISSUE THREAD

**Issue by wyu** [PNNL-Comp-Mass-Spec/Mzid-To-Tsv-Converter#1]
Following the discussion in the MSGF+ repo, I attempted to convert a large mzid (2.8GB) file from a timsTOF MS/MS dataset. The conversion stopped with the error below.

PS Z:\Data\timsTOF> ..\..\Software\MzidToTsvConverter\net45\MzidToTsvConverter.exe -mzid:.\HeLa00050505.mzid -sd -qvalue
:0.01
Using options:
mzid path: ".\HeLa00050505.mzid"
tsv path: ".\HeLa00050505.tsv"
Unroll results: False
Show decoy: True
Single result per spectrum: False
Filtering results by score
Max QValue: 0.01

------------------------------------------------------------------------------
MZID PARSE ERROR: Cannot add duplicate peptideEvidence id "PepEv_33190_VNPTVFFDIAVDGEPLGR_1"!

Stack trace:
  MzidToTsvConverter.MzidToTsvConverter.ConvertToTsv
  PSI_Interface.IdentData.SimpleMZIdentMLReader.ReadLowMem

  PSI_Interface.IdentData.SimpleMZIdentMLReader.ReadSequenceCollection
  PSI_Interface.IdentData.SimpleMZIdentMLReader.ReadPeptideEvidence
------------------------------------------------------------------------------

MZID PARSE ERROR: Cannot add duplicate peptideEvidence id "PepEv_33190_VNPTVFFDIAVDGEPLGR_1"!

This type of error is usually caused by an error in the MZID output.

Conversion finished!

**Comment by FarmGeek4Life** [comment]
There is the '-skipDupIds' option that will at least continue to produce the TSV output file; the real issue is one where we now have some example files to determine and solve the issue ([MSGFPlus #49](https://github.com/MSGFPlus/msgfplus/issues/49)).

**Comment by FarmGeek4Life** [comment]
The latest update to MSGFPlus should fix this issue (release 2019.02.27)
