### ISSUE TITLE
Retention time

### ISSUE THREAD

**Issue by yafeng** [PNNL-Comp-Mass-Spec/Mzid-To-Tsv-Converter#2]
Can you please add retention time in the TSV table generated by the converter? It is really important to have it.  Thanks!

**Comment by FarmGeek4Life** [comment]
Code was just pushed that adds the retention time (as column 'ScanTime(Min)') to the output by default, with an option to disable it. I will upload binaries tomorrow.

**Comment by yafeng** [comment]
@FarmGeek4Life Thank you!

**Comment by FarmGeek4Life** [comment]
Binaries can now be downloaded for [Release 1.3.0](https://github.com/PNNL-Comp-Mass-Spec/Mzid-To-Tsv-Converter/releases/tag/v1.3.0)
