### ISSUE TITLE
How to export the starting position of each peptide?

### ISSUE THREAD

**Issue by ghost** [PNNL-Comp-Mass-Spec/Mzid-To-Tsv-Converter#7]

**Comment by KKKKK-tech** [comment]
`<PeptideEvidence dBSequence_ref="DBSeq3799096" peptide_ref="Pep_KPATPAEDDEDDDIDLFGS+80DNEEEDK" start="144" end="169" pre="K" post="E" isDecoy="false" id="PepEv_3799239_KPATPAEDDEDDDIDLFGS+80DNEEEDK_144"/>`
